
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from logic import cargarboton, seleccionarCarpeta

OUTPUT_PATH = Path(__file__).parent
#Cambiar el path a el directorio correspondiente en donde se ubica la carpeta assets del proyecto
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\kv901\OneDrive\Desktop\LectorOCR\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def iniciar_gui():
    window = Tk()
    window.geometry("550x700")
    window.configure(bg="#135A4A")

    canvas = Canvas(
        window,
        bg="#135A4A",
        height=700,
        width=550,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
    canvas.create_rectangle(0.0, 0.0, 550.0, 129.0, fill="#3BA68B", outline="")

    image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
    canvas.create_image(482.0, 64.0, image=image_image_1)

    image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
    canvas.create_image(205.0, 64.0, image=image_image_2)

    entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
    canvas.create_image(235.0, 342.5, image=entry_image_1)

    entry_1 = Entry(
        bd=0,
        bg="#6DCDAD",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(x=69.0, y=320.0, width=332.0, height=43.0)

    image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
    canvas.create_image(281.0, 276.0, image=image_image_3)

    selector = seleccionarCarpeta(entry_1)

    button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=selector.ejecutar_procesamiento,
        relief="flat"
    )
    button_1.place(x=139.0, y=424.0, width=272.0, height=61.0)

    button_image_2 = cargarboton.create_button_with_background()
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=selector.seleccionar_carpeta_tickets,
        relief="flat"
    )
    button_2.place(x=406.0, y=301.0, width=88.0, height=87.0)

    window.resizable(False, False)
    window.mainloop()

if __name__ == "__main__":
    from multiprocessing import freeze_support
    freeze_support()
    iniciar_gui()
